env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'google'
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2016
  sourceType: module
plugins:
  - vue
rules: {}
