AsciiComments:
 Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 150
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'

Metrics/MethodLength:
  Exclude:
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

Style/MixinUsage:
  Exclude:
      - 'bin/**/*'

Style/NumericLiterals:
  Exclude:
        - 'db/**/*'
