AlignHash:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

AsciiComments:
 Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*'
    - 'db/schema.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 150
  Exclude:
    - 'bin/*'
    - 'config/routes.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'

Metrics/MethodLength:
  Exclude:
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

Style/MixinUsage:
  Exclude:
      - 'bin/**/*'

Style/NumericLiterals:
  Exclude:
        - 'db/**/*'
